### PR TITLE
[KED-2743] Send generic event with additional properties

### PR DESCRIPTION
**Pull request by lorenabalan**

### CODE REVIEW

**Review by datajoely — APPROVED** [review]

**Comment by datajoely** [comment]
Can we also include the `hostname` in the payload? It's used in the heap push event, but not accessible once we retrieve the data
https://github.com/quantumblacklabs/kedro-telemetry/blob/a71bb69a7ee42ae402e8cc47a64d24a339e14e8a/kedro_telemetry/plugin.py#L97

**Comment by lorenabalan** [comment]
> Can we also include the `hostname` in the payload? It's used in the heap push event, but not accessible once we retrieve the data

I can add it to the properties but that's interesting, you can't link back an "event" to the "user identity"?

**Comment by datajoely** [comment]
I worked it out - it's spread across two tables in SQL, but it's a little unintuitive. Essentially heap does a user anonymisation step so that you work with their `USER_ID` in SQL and the unmasked version is another table. This is clever - but a bit annoying when it's doubly anonymised!

**Comment by lorenabalan** [comment]
@datajoely nice one! 💯  I can leave it as is then, right? I think it's more in the spirit of the plugin but let me know if I misunderstood.

**Review by datajoely — APPROVED** [review]
Good to go 💯

**Review by ignacioparicio — APPROVED** [review]
LGTM! Thanks for the additional inline comments and type hints :clap:

**Pull request merged**
